server:
  port: 13000
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    name: gulimall-search
  thymeleaf:
    cache: false
    #  redis
  redis:
    host: 192.168.19.130
    password: 123456
    port: 6379
  session:
    store-type: redis


