server:
  port: 12000


spring:
  application:
    name: gulimall-third-part
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#        配置阿里云oss
    alicloud:
      access-key: LTAI5tDVZ8QkLCsrKYPxt1fz
      secret-key: ihxyZqIYjuvoO5fwRQwsBac2XOAbaX
      oss:
        endpoint: oss-cn-guangzhou.aliyuncs.com
        bucket: xushuhan-mall
      sms:
        host: http://dingxin.market.alicloudapi.com
        path: /dx/sendSms
        appCode: 60585ae5a76445b8badf93f727d36ec1
        tpl_id: TP1711063

