server:
  port: 15000
spring:
  application:
    name: gulimall-cart
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  #缓存
  thymeleaf:
    cache: false
  #  redis
  redis:
    host: 192.168.19.130
    password: 123456
    port: 6379
  session:
    store-type: redis #配置session的存储地方
    redis:
      namespace: spring:session #配置session存储在redis中的key前缀

#异步线程的配置：com.han.gulimall.cart.config.ThreadPoolConfigProperties
gulimall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10
